In [6]:
import os
import pandas as pd

In [7]:
df = pd.read_csv("results-nomin.tsv", sep="\t", header="infer")
df

,benchmark,instance,executable,solver,maximization,constraint,reason,lazy,fileout,cost,...,status,exit_code,real,time,user,system,memory,#max,#win,Column 1
0,GraphColouring,0001-graph_colouring-125-0_1200.asp,clingo-plainmaximize-amo,clingo,plainmaximize,amo,none,none,results/GraphColouring/0001-graph_colouring-12...,"2,076.00",...,outof time,11,"1,200.56","1,200.29","1,200.02",0.27,142.80,2304,0,NaN
1,GraphColouring,0001-graph_colouring-125-0_2400.asp,clingo-plainmaximize-amo,clingo,plainmaximize,amo,none,none,results/GraphColouring/0001-graph_colouring-12...,"2,076.00",...,outof time,11,"1,200.45","1,200.37","1,200.16",0.21,119.70,2304,0,NaN
2,GraphColouring,0001-graph_colouring-125-0_3600.asp,clingo-plainmaximize-amo,clingo,plainmaximize,amo,none,none,results/GraphColouring/0001-graph_colouring-12...,"2,076.00",...,outof time,11,"1,200.49","1,200.14","1,199.80",0.34,119.50,2304,0,NaN
3,GraphColouring,0001-graph_colouring-125-0_4800.asp,clingo-plainmaximize-amo,clingo,plainmaximize,amo,none,none,results/GraphColouring/0001-graph_colouring-12...,"2,076.00",...,outof time,11,"1,200.25","1,200.14","1,199.29",0.85,118.70,2304,0,NaN
4,GraphColouring,0001-graph_colouring-125-0_6000.asp,clingo-plainmaximize-amo,clingo,plainmaximize,amo,none,none,results/GraphColouring/0001-graph_colouring-12...,"2,076.00",...,outof time,11,"1,201.14","1,200.95","1,200.62",0.33,119.50,2304,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,TSP,095-490-tsp.asp,clingo-amomaximize-amo-nomin,clingo,amomaximize,amo,nomin,none,results/TSP/095-490-tsp.asp.out,"26,599.00",...,outof time,29,"1,205.49","1,201.04","1,179.25",21.79,"3,060.90",26599,1,1
1296,TSP,096-495-tsp.asp,clingo-amomaximize-amo-nomin,clingo,amomaximize,amo,nomin,none,results/TSP/096-495-tsp.asp.out,"26,421.00",...,outof time,29,"1,206.32","1,200.95","1,173.00",27.95,"3,242.80",26421,1,1
1297,TSP,097-500-tsp.asp,clingo-amomaximize-amo-nomin,clingo,amomaximize,amo,nomin,none,results/TSP/097-500-tsp.asp.out,"25,988.00",...,outof time,10,"1,207.60","1,201.07","1,179.29",21.78,"3,091.30",25988,1,1
1298,TSP,098-505-tsp.asp,clingo-amomaximize-amo-nomin,clingo,amomaximize,amo,nomin,none,results/TSP/098-505-tsp.asp.out,"26,987.00",...,outof time,29,"1,207.51","1,201.08","1,175.63",25.45,"3,163.60",27401,0,0.9848916138
1299,TSP,099-510-tsp.asp,clingo-amomaximize-amo-nomin,clingo,amomaximize,amo,nomin,none,results/TSP/099-510-tsp.asp.out,"25,842.00",...,outof time,29,"1,208.17","1,200.89","1,171.77",29.12,"3,339.20",25934,0,0.9964526701

In [8]:
df.columns

Index(['benchmark', 'instance', 'executable', 'solver', 'maximization',
       'constraint', 'reason', 'lazy', 'fileout', 'cost', 'f1', 'f2', 'status',
       'exit_code', 'real', 'time', 'user', 'system', 'memory', '#max', '#win',
       'Column 1'],
      dtype='object')

In [11]:
version = "nomin"

df = pd.read_csv(f"old_version_results/results-{version}.tsv", sep="\t", header="infer")

df = df[["benchmark", "instance", "executable", "cost", "status", "exit_code", "real", "time", "user", "system", "memory"]]

df.insert(0, "execid", version)
df

,execid,benchmark,instance,executable,cost,status,exit_code,real,time,user,system,memory
0,nomin,GraphColouring,0001-graph_colouring-125-0_1200.asp,clingo-plainmaximize-amo,"2,076.00",outof time,11,"1,200.56","1,200.29","1,200.02",0.27,142.80
1,nomin,GraphColouring,0001-graph_colouring-125-0_2400.asp,clingo-plainmaximize-amo,"2,076.00",outof time,11,"1,200.45","1,200.37","1,200.16",0.21,119.70
2,nomin,GraphColouring,0001-graph_colouring-125-0_3600.asp,clingo-plainmaximize-amo,"2,076.00",outof time,11,"1,200.49","1,200.14","1,199.80",0.34,119.50
3,nomin,GraphColouring,0001-graph_colouring-125-0_4800.asp,clingo-plainmaximize-amo,"2,076.00",outof time,11,"1,200.25","1,200.14","1,199.29",0.85,118.70
4,nomin,GraphColouring,0001-graph_colouring-125-0_6000.asp,clingo-plainmaximize-amo,"2,076.00",outof time,11,"1,201.14","1,200.95","1,200.62",0.33,119.50
...,...,...,...,...,...,...,...,...,...,...,...,...
1295,nomin,TSP,095-490-tsp.asp,clingo-amomaximize-amo-nomin,"26,599.00",outof time,29,"1,205.49","1,201.04","1,179.25",21.79,"3,060.90"
1296,nomin,TSP,096-495-tsp.asp,clingo-amomaximize-amo-nomin,"26,421.00",outof time,29,"1,206.32","1,200.95","1,173.00",27.95,"3,242.80"
1297,nomin,TSP,097-500-tsp.asp,clingo-amomaximize-amo-nomin,"25,988.00",outof time,10,"1,207.60","1,201.07","1,179.29",21.78,"3,091.30"
1298,nomin,TSP,098-505-tsp.asp,clingo-amomaximize-amo-nomin,"26,987.00",outof time,29,"1,207.51","1,201.08","1,175.63",25.45,"3,163.60"
1299,nomin,TSP,099-510-tsp.asp,clingo-amomaximize-amo-nomin,"25,842.00",outof time,29,"1,208.17","1,200.89","1,171.77",29.12,"3,339.20"

In [13]:
df.to_csv(f"results/{version}.tsv", sep="\t", header=False, index=False)